lib/lta_bus_timings_web/router.ex
defmodule LtaBusTimingsWeb.Router do
  use LtaBusTimingsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LtaBusTimingsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LtaBusTimingsWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/favourite", FavouriteController, only: [:create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", LtaBusTimingsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: LtaBusTimingsWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/lta_bus_timings_web/templates/page/bus_details.html.heex
<%= if @bus["EstimatedArrival"] != "" do %>
    <td class={@bus["Load"]}>
    <div class="bus-card">
        <div class="extra-icons">
            <!-- <%= if @bus["Feature"] do %>
                <%= @bus["Feature"] %>
            <% end %> -->
            <%= @bus["Type"] %>
        </div>
        <div>
            <%= seconds_till_arrival @bus["EstimatedArrival"] %>
        </div>
    </div>
    </td>
<% else %>
    <td class="no-bus"></td>
<% end %>

lib/lta_bus_timings_web/templates/page/index.html.heex
<section>
  <form>
    <label for="stop_id" class="inline">Stop ID: </label>
    <input type="number" id="stop_id" name="stop_id" value={@stop_id} class="inline">
    <input type="submit" value="Submit" class="inline">
  </form>
</section>

<section>
    <h1><%= bus_stop_description(@stop_id) %></h1>
    <table class="bus-timings">
    <tr>
      <th>Service No</th>
      <th>Next Bus</th>
      <th>Next Bus 2</th>
      <th>Next Bus 3</th>
    </tr>
    <%= for service <- @services do %>
      <tr>
        <td><%= service["ServiceNo"] %></td>
        <%= render("bus_details.html", bus: service["NextBus"]) %>
        <%= render("bus_details.html", bus: service["NextBus2"]) %>
        <%= render("bus_details.html", bus: service["NextBus3"]) %>
        <td>
        <%= if favourited_service?(@favourited_services, service["ServiceNo"]) do %>
          <%= button "unfavourite", to: Routes.favourite_path(@conn, :delete, "{\"stop_id\": \"#{@stop_id}\", \"service\": \"#{service["ServiceNo"]}\"}"),
            method: :delete %>
        <% else %>
          <%= button "favourite", to: Routes.favourite_path(@conn, :create, %{stop_id: @stop_id, service: service["ServiceNo"]}),
            method: :post %>
        <% end %>
        </td>
      </tr>
    <% end %>    
  </table>
</section>

<section>
<h3>Favourites</h3>
 <%= for stop_id <- @favourite_stops do %>
    <a href={Routes.page_path(@conn, :index, %{"stop_id" => stop_id})}>
      <div><%= stop_id %> <%= bus_stop_description(stop_id) %></div>
    </a>
  <% end %>
  </section>